const women_clothes = {
  1: 'voan',
  2: 'chinos',
  3: 'Cotton',
  4: 'Denim',
  5: 'Lông vũ',
  6: 'Nỉ',
  7: 'Nỉ mỏng',
  8: 'Lông cừu',
  9: 'lông',
  10: 'kaki',
  11: 'Đan',
  12: 'Ren',
  13: 'Da',
  14: 'Lanh',
  15: 'Nylon',
  16: 'Khác',
  17: 'bông',
  18: 'Lụa',
  19: 'Sợi tổng hợp',
  20: 'Sợi dệt',
  21: 'Nhung',
  22: 'Len',
}
export default women_clothes
