const materials = {
  women_clothes: {
    1: 'voan',
    2: 'chinos',
    3: 'Cotton',
    4: 'Denim',
    5: 'Lông vũ',
    6: 'Nỉ',
    7: 'Nỉ mỏng',
    8: 'Lông cừu',
    9: 'lông',
    10: 'kaki',
    11: 'Đan',
    12: 'Ren',
    13: 'Da',
    14: 'Lanh',
    15: 'Nylon',
    16: 'Khác',
    17: 'bông',
    18: 'Lụa',
    19: 'Sợi tổng hợp',
    20: 'Sợi dệt',
    21: 'Nhung',
    22: 'Len',
  },
  men_clothes: {
    1: 'chinos',
    2: 'Cotton',
    3: 'Denim',
    4: 'Lông vũ',
    5: 'Nỉ',
    6: 'Nỉ mỏng',
    7: 'Lông cừu',
    8: 'lông',
    9: 'kaki',
    10: 'Đan',
    11: 'Da',
    12: 'Lanh',
    13: 'Nylon',
    14: 'Khác',
    15: 'bông',
    16: 'Sợi tổng hợp',
    17: 'Sợi dệt',
    18: 'Len',
  },
  hat: {
    1: 'Canvas',
    2: 'Dệt Kim',
    3: 'Ren',
    4: 'Da',
    5: 'Khác',
    6: 'Lụa',
    7: 'Len',
  },
  fashion_accessories: {
    1: 'Kim cương',
    2: 'Sợi vải',
    3: 'Đá Ngọc Bích',
    4: 'Vàng',
    5: 'Da',
    6: 'Mạ kim loại',
    7: 'Khác',
    8: 'Ngọc trai',
    9: 'bạch kim',
    10: 'Bạc',
    11: 'Thép',
    12: 'Titanium, Bismuth & Nam châm',
  },
  belt: {
    1: 'Canvas',
    2: 'Dệt Kim',
    3: 'Ren',
    4: 'Da',
    5: 'Khác',
    6: 'Lụa',
    7: 'Len',
  },
  boots: {
    1: 'Sợi tổng hợp',
    2: 'Da',
    3: 'Sợi vải',
    4: 'Da lộn',
    5: 'Cao su',
    6: 'Khác',
    7: 'Len',
    8: 'chinos',
    9: 'Cotton',
    10: 'Denim',
    11: 'Nỉ',
    12: 'Lông cừu',
    13: 'lông',
    14: 'Nỉ mỏng',
    15: 'Đan',
    16: 'Lanh',
    17: 'Nylon',
    18: 'voan',
    19: 'Jersey',
    20: 'Nỉ mỏng',
    21: 'tơ nhân tạo',
    22: 'Lụa',
    23: 'Đồ lặn',
    24: 'Vải dù',
    25: 'Nhựa',
    26: 'Cối',
    27: 'Canvas',
    28: 'Da PU',
  },
  shoes_and_sandals: {
    1: 'Cotton',
    2: 'Canvas',
    3: 'Polyester',
    4: 'Nylon',
    5: 'Da',
    6: 'Da PU',
    7: 'PVC',
    8: 'Nhựa',
    9: 'Sợi tổng hợp',
    10: 'cashmere',
    11: 'Đan',
    12: 'Lanh',
    13: 'Khác',
    14: 'Sợi dệt',
    15: 'lông',
    16: 'Denim',
    17: 'Len',
    18: 'Da lộn',
    19: 'Cối',
    20: 'Cao su',
    21: 'chinos',
    22: 'Nỉ',
    23: 'Lông cừu',
    24: 'Nỉ mỏng',
    25: 'voan',
    26: 'Jersey',
    27: 'tơ nhân tạo',
    28: 'Lụa',
    29: 'Đồ lặn',
    30: 'Vải dù',
  },
  suitcase_and_travel_bag: {
    1: 'Da',
    2: 'Khác',
    3: 'Nhựa',
    4: 'Sợi dệt',
  },
  wallets: {
    1: 'Canvas',
    2: 'Da',
    3: 'Nylon',
    4: 'Khác',
    5: 'PVC',
    6: 'Sợi tổng hợp',
    7: 'Sợi dệt',
  },
  watch: {
    1: 'Hợp kim',
    2: 'Gốm sứ',
    3: 'Khác',
    4: 'Nhựa',
    5: 'Thép không gỉ',
    6: 'Titanium',
  },
  blanket: {
    1: 'Tre',
    2: 'Cotton',
    3: 'Lông vũ',
    4: 'Lông cừu',
    5: 'Lyocell',
    6: 'Microfiber',
    7: 'Len',
    8: 'Polyester',
  },
  motobike_accessory: {
    1: 'Canvas',
    2: 'Cotton',
    3: 'Sợi vải',
    4: 'Da',
    5: 'Kim loại',
    6: 'cao su tổng hợp',
    7: 'Nhựa',
    8: 'Cao su',
    9: 'Vinyl',
  },
  helmet: {
    1: 'Sợi tổng hợp',
    2: 'Kim loại',
    3: 'Thép',
    4: 'Hợp kim',
    5: 'Canvas',
    6: 'cashmere',
    7: 'Cotton',
    8: 'Dệt Kim',
    9: 'Ren',
    10: 'Da',
    11: 'Khác',
    12: 'Lụa',
    13: 'Len',
    14: 'Lông cừu',
    15: 'Lanh',
    16: 'Nylon',
    17: 'kaki',
    18: 'chinos',
    19: 'Nỉ mỏng',
    20: 'Denim',
    21: 'Nhung',
    22: 'Lông vũ',
    23: 'Đan',
    24: 'voan',
  },
  car_accessory: {
    1: 'Canvas',
    2: 'Cotton',
    3: 'Sợi vải',
    4: 'Da',
    5: 'Kim loại',
    6: 'cao su tổng hợp',
    7: 'Nhựa',
    8: 'Cao su',
    9: 'nan',
    10: 'Vinyl',
  },
  toys_and_collectibles: {
    1: 'PVC',
    2: 'Khác',
    3: 'Nhựa',
    4: 'Nylon',
    5: 'Canvas',
    6: 'Cotton',
    7: 'Polyester',
    8: 'Giấy',
    9: 'Sợi tổng hợp',
    10: 'Kim loại',
    11: 'Thép',
    12: 'Hợp kim',
    13: 'cashmere',
    14: 'Dệt Kim',
    15: 'Ren',
    16: 'Da',
    17: 'Lụa',
    18: 'Len',
    19: 'Cao su',
    20: 'Kim cương',
    21: 'Sợi vải',
    22: 'Đá Ngọc Bích',
    23: 'Ngọc trai',
    24: 'Bạc',
  },
}

export default materials
