// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CBanner: typeof import('./components/CBanner.vue')['default']
    CBrand: typeof import('./components/CBrand.vue')['default']
    CDemo1: typeof import('./components/CDemo1.vue')['default']
    CDemo2: typeof import('./components/CDemo2.vue')['default']
    CExtension: typeof import('./components/CExtension.vue')['default']
    CFooter: typeof import('./components/CFooter.vue')['default']
    CHead: typeof import('./components/CHead.vue')['default']
    CList: typeof import('./components/CList.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    CProduct: typeof import('./components/CProduct.vue')['default']
    CSearch: typeof import('./components/CSearch.vue')['default']
    CService: typeof import('./components/CService.vue')['default']
    CSwipper: typeof import('./components/CSwipper.vue')['default']
    LMenu: typeof import('./components/LMenu.vue')['default']
    README: typeof import('./components/README.md')['default']
    RMenu: typeof import('./components/RMenu.vue')['default']
  }
}

export { }
